name: farm-automation
version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - farmnet

  mqtt-web-client:
    image: nginx:alpine
    container_name: mqtt-web-client
    restart: always
    ports:
      - "8088:80"
    volumes:
      - ./mqtt-web-client:/usr/share/nginx/html
    networks:
      - farmnet

  backend:
    build: ../backend
    container_name: backend
    restart: always
    env_file:
      - ../backend/.env.development
    ports:
      - "8000:8000"
    networks:
      - farmnet

  frontend:
    build: ../frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - farmnet

  mqtt-status-worker:
    build: ../backend
    container_name: mqtt-status-worker
    restart: always
    env_file:
      - ../backend/.env.development
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "-m", "app.mqtt_status_worker"]
    networks:
      - farmnet

networks:
  farmnet:
    driver: bridge 