"""add_is_deleted_to_device

Revision ID: 5bf6fe2a7bdf
Revises: 2986dd0a280c
Create Date: 2025-06-26 13:30:52.169539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bf6fe2a7bdf'
down_revision: Union[str, Sequence[str], None] = '2986dd0a280c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'is_deleted')
    # ### end Alembic commands ###
