"""change tenant status to boolean active

Revision ID: eae7c3484709
Revises: 7369eae75075
Create Date: 2025-06-25 17:09:14.661778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eae7c3484709'
down_revision: Union[str, Sequence[str], None] = '7369eae75075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('active', sa.Boolean(), nullable=False))
    op.drop_column('tenants', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('status', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('tenants', 'active')
    # ### end Alembic commands ###
